variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/frontend

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - dev
  tags:
    - schildichat_kanban_frontend_runner_tag
  script:
    - cp ../.env .env
    - docker-compose -p shildichat_kanban_frontend build

deploy:
  stage: deploy
  only:
    - dev
  tags:
    - schildichat_kanban_frontend_runner_tag
  script:
    - cp ../.env .env
    - docker-compose -p shildichat_kanban_frontend down
    - docker-compose -p shildichat_kanban_frontend up -d
